### ISSUE TITLE
Use __builtin_ia32_addsubpd instead of implicit

### ISSUE THREAD

**Issue by p0nce** [AuburnSounds/intel-intrinsics#105]
LDC 1.29+ doesn't generate addsubpd unless we use the builtin.
- [x] All "addsub" operations should use a builtin if any exist.

**Comment by p0nce** [comment]
Reference: https://github.com/AuburnSounds/Dplug/issues/703

Clearly one case of the instruction generating in the small, but not when inlined. When there is a builtin available, it should be used.

**Comment by JohanEngelen** [comment]
finally i have a proof that intel-intrinsics needs assembly output testing, so I can add this remark:  add something like LDC's lit-based testsuite   ;)

**Comment by p0nce** [comment]
Most intrinsics being added have been godbolted in a lot of possible scenario, the thing that changed is that now I think builtins are better when available. :) wrk in -O0 and faster for the compiler

**Comment by p0nce** [comment]
But seriously, it's not often clear what instruction should be checked for.
For example `_mm_setr_epi32(4, 5, 8, 9)` will always be inlined to a `movaps, xmm-constant`, etc.
