### ISSUE TITLE
Different speed results on macOS(M1) and Linux(X86_64)

### ISSUE THREAD

**Issue by cyrusmsk** [AuburnSounds/intel-intrinsics#121]
I wrote several implementations of the same problem (actually it were ports from other languages).

zero - simple code without usage of SIMD
first - implementation with SIMD
second - another implementation with SIMD

For building I'm using simple 'dub build --build=release --compiler=ldc2'. In dub.json I have intel-intrinsics dependency, and for x86_64 I've added "dflags-ldc": ["-mattr=+sse3,+ssse3,+sse4.1,+sse4.2,+avx", "-mcpu=native"]. For M1 (arm) no extra flags are used. Currently I'm interested only in LDC compiler.

So results on my MBP (M1-Pro):
` /usr/bin/time ./zero 10
73196
Pfannkuchen(10) = 38
        0,31 real         0,31 user         0,00 sys
 /usr/bin/time ./first 10 
73196
Pfannkuchen(10) = 38
        0,13 real         0,13 user         0,00 sys
 /usr/bin/time ./second 10
73196
Pfannkuchen(10) = 38
        0,37 real         0,37 user         0,00 sys`
Second version is little bit slower than zero, but the first is much faster.
However when I'm running on GitHub Actions x86_64 Linux machine the zero version is much faster even of the first version.
[GitHub Actions job details](https://github.com/cyrusmsk/simd_d_testrun/actions/runs/3976000840/jobs/6816210695)

Is it something wrong with my configuration of dub?

**Comment by p0nce** [comment]
Most likely issues:
- **you need to use `dub --combined`, else most of the intrinsics won't get inlined**.
- Why not use `-b release-nobounds`? more speed
- Be sure your benchmark has low variance, that it gives about the same timings when run multiple times.
- Not sure about measuring in the cloud, your machine is virtualized there.
- On M1, be sure to use `-a arm64-apple-macos` else it's JITed

**Comment by p0nce** [comment]
Oh I've found your repo and indeed the second one is not necessarily better, let's see...

**Comment by cyrusmsk** [comment]
Thank you for your answer. It seems situation is good now
Maybe it is better to add somewhere on dub's package page or GitHub README file information about '--combined' flag

**Comment by p0nce** [comment]
Absolutely, I will add this.
