### ISSUE TITLE
Undefined identifier _m256 in avxintrin

### ISSUE THREAD

**Issue by KytoDragon** [AuburnSounds/intel-intrinsics#124]
There is a typo in the definition of the "_mm256_cmp_ps" template in avxintrin.d, which causes a compilation error:

```
intel-intrinsics-1.11.1\intel-intrinsics\source\inteli\avxintrin.d(829,7): Error: undefined identifier `_m256`, did you mean alias `__m256`?
```

Templates "_mm_cmp_sd" and "_mm_cmp_ss" are also affected (the cast in these functions should be "__m128d" and "__m128", not "_m256").

**Comment by p0nce** [comment]
Hello, this is fixed in v1.11.12
If you use this lib do not hesitate to mention for what so that we can stuff it in the README :)
