### ISSUE TITLE
cant build release-nobounds with dmd on linux for x86_64 target

### ISSUE THREAD

**Issue by abaga129** [AuburnSounds/intel-intrinsics#18]
DMD version - v2.084.0
Dub version - 1.13.0

This is a very specific case but if I use `-a=x86_64`, `-b=release-nobounds`, and `compiler=dmd` on linux, it will fail.
`dub build --build=release-nobounds --arch=x86_64 --compiler=dmd`

Output
```
intel-intrinsics 1.0.13: building configuration "library"...
tym = x1d
Illegal instruction (core dumped)
dmd failed with exit code 132.
```

I'm happy to provide any more details you may need!

**Comment by p0nce** [comment]
This is https://github.com/AuburnSounds/intel-intrinsics/issues/17 

I fixed it in intel-intrinsics already but forgot to push a tag.
Now this is on the DUB registry with tag v1.0.31
So if you `dub upgrade` you should have the latest intel-intrinsics, which is green.

**Comment by abaga129** [comment]
Excellent! Sorry for opening a duplicate issue.  I didnt see you had already addressed it.

**Comment by p0nce** [comment]
No problem it was my fault for not pushing a tag and updating the dub registry!
