### ISSUE TITLE
Non-temporal moves are not really non-temporal moves

### ISSUE THREAD

**Issue by p0nce** [AuburnSounds/intel-intrinsics#20]
```
// Can't implement non-temporal store with LDC inlineIR since !nontemporal
// needs some IR outside this function that would say:
//
//  !0 = !{ i32 1 }
//
// It's a LLVM IR metadata description.
```

**Comment by p0nce** [comment]
Probably possible with the new `__IREx_pure` from LDC 1.13 onwards

**Comment by charlesgregory** [comment]
This should be possible using the LDC asm template:
```
void _mm_stream_pi (__m64* mem_addr, __m64 a)
{
    __asm("movntq $1,$0", "*m,y", mem_addr, a);
}
```
You could use a normal move for just DMD.

**Comment by p0nce** [comment]
Yes, good idea! Thanks.

**Comment by p0nce** [comment]
Now possible since LDC 1.13, so this bug will be solved.

**Comment by p0nce** [comment]
Code	Fichier	Ligne	Colonne
- [ ] `_mm_stream_si64`
- [ ] `_mm_stream_si32`
- [x] `_mm_stream_si128`
- [x] `_mm_stream_ps`
- [ ] `_mm_stream_pi6`
- [x] `_mm_stream_pd`
- [ ] `_mm_stream_load_si128`

**Comment by p0nce** [comment]
Woohoo, non-temporal moves are non-temporal now (said noone ever)
