### ISSUE TITLE
Auto generating default implementation

### ISSUE THREAD

**Issue by burner** [AuburnSounds/intel-intrinsics#23]
so this side here
https://software.intel.com/sites/landingpage/IntrinsicsGuide/#

gives pseudo code for all operations in all form mmx to avx-512.

for example for the operation _mm_addsub_pd the following code is given:
```
FOR j := 0 to 1
	i := j*64
	IF (j is even) 
		dst[i+63:i] := a[i+63:i] - b[i+63:i]
	ELSE
		dst[i+63:i] := a[i+63:i] + b[i+63:i]
	FI
ENDFOR
```

parsing that and putting out D would allow to generate default implementation for all inbuild operations.
The performance will be bad, but the default would only be called if the cpu operation is not available.

Thoughts?

**Comment by p0nce** [comment]
Mmm that must explain why AVX-512 (and AVX in general) has such a high number of intrinsics.
I'm not sure what to think of it, probably Intel introduced it for its own tests!
I think it's significant work to build that small compiler though.

I was thinking of avoiding AVX512 completely (possibly AVX) because of how unrealistic it is to use it in intrinsics form, people tend to use the compiler switches instead with SSE intrinsics. One of the interest of cutting the link to `ldc.gccbuiltins_x86` is being able to enable CPU features regardless of particular instructions.

**Comment by burner** [comment]
Building the compiler is not that hard, I'm already able to parse 5148 of 6180 functions. It took me ~2 hours. The code generation should be very easy as well.

From what I have seen so, the language has nothing D does not have.
I codegen should therefore not be that hard.

**Comment by p0nce** [comment]
OK you're way faster than me! Let's see tomorrow at the hackathon

**Comment by burner** [comment]
I had a lexer that was mostly there and a parser generator, so the work was mostly done to start with

**Comment by p0nce** [comment]
Well the definition language has macro definitions, for loops, scoping... it's hard

**Comment by burner** [comment]
from what I see, these behave like the D equivalents.

**Comment by burner** [comment]
https://github.com/burner/-Intel-Intrinsics-generator

getting there

**Comment by burner** [comment]
now it is there, forgot to push

**Comment by p0nce** [comment]
Thanks Robert! I will try it in the following week and see how it can fit.

**Comment by p0nce** [comment]
https://software.intel.com/sites/landingpage/IntrinsicsGuide/#techs=SSE3&expand=221

An example of wrong pseudo-code:
```
FOR j := 0 to 1
	i := j*64
	IF (j % 1 == 0)  // should be IF (j % 2 == 0)
		dst[i+63:i] := a[i+63:i] - b[i+63:i]
	ELSE
		dst[i+63:i] := a[i+63:i] + b[i+63:i]
	FI
ENDFOR
```

**Comment by burner** [comment]
do they have an issue tracker, do post this issue?

**Comment by p0nce** [comment]
I don't know of one yet. I will post wrong pseudocode here, in case we can report it.

```
(addsubps)
FOR j := 0 to 3
	i := j*32
	IF (j % 1 == 0) // should be j % 2
		dst[i+31:i] := a[i+31:i] - b[i+31:i]
	ELSE
		dst[i+31:i] := a[i+31:i] + b[i+31:i]
	FI
ENDFOR
```

**Comment by burner** [comment]
sounds like a plan

**Comment by p0nce** [comment]
Closing this as I don't feel it's a good . The thing that takes times is not really writing the algorithm, it's more finding the relevant builtins, fixing tests, writing tests.
