### ISSUE TITLE
Does not compile with latest gdc

### ISSUE THREAD

**Issue by moon-chilled** [AuburnSounds/intel-intrinsics#41]
Running the latest version of gdc (`ibuclaw/gdc` branch of gcc upstream), I get [these](http://ix.io/26XH) compilation errors.

**Comment by p0nce** [comment]
Is there any (windows) build of this compiler? Is this compiler released?

**Comment by moon-chilled** [comment]
I don't think there's any build of it; I had to build it from source.

Actually, I'm not entirely sure where the compiler source is now.  There was an `ibuclaw/gdc` branch in the mainline GCC repository, but it's now [nowhere to be found](https://gcc.gnu.org/git/?p=gcc.git;a=heads).  (I can upload it if you want to try to use it to test.)  That was basically gdc merged with ddmd 2.089.  It isn't released; probably it will be released with gcc 10.

**Comment by p0nce** [comment]
Yes, if you have any build of it (Linux, mac, windows) I'd be happy to have it :)

**Comment by moon-chilled** [comment]
Linux build is [here](http://please.dont.thwack.me/gdc.tar.gz) (extract in `$HOME`, make a shellscript called `gdc` looking like [this](http://sprunge.us/ZVRVgk)).

Source code I'm using is [here](https://github.com/moon-chilled/gdc-d2089)

**Comment by p0nce** [comment]
Thank you!

**Comment by p0nce** [comment]
Unfortunately I don't manage to run GDC:
```
ponce@x220:~$ gdc
/usr/bin/ld: cannot find crt1.o: No such file or directory
/usr/bin/ld: cannot find crti.o: No such file or directory
/usr/bin/ld: /home/ponce/.gdcinstall/lib/../lib64/libgphobos2.a(curl.o): unable to initialize decompress status for section .debug_info
/usr/bin/ld: /home/ponce/.gdcinstall/lib/../lib64/libgphobos2.a(curl.o): unable to initialize decompress status for section .debug_info
/usr/bin/ld: /home/ponce/.gdcinstall/lib/../lib64/libgdruntime2.a(atomic.o): unable to initialize decompress status for section .debug_info
/usr/bin/ld: /home/ponce/.gdcinstall/lib/../lib64/libgdruntime2.a(atomic.o): unable to initialize decompress status for section .debug_info
/usr/bin/ld: /home/ponce/.gdcinstall/bin/../lib/gcc/x86_64-pc-linux-gnu/10.0.0/libgcc.a(_muldi3.o): unable to initialize decompress status for section .debug_info
/usr/bin/ld: /home/ponce/.gdcinstall/bin/../lib/gcc/x86_64-pc-linux-gnu/10.0.0/libgcc.a(_muldi3.o): unable to initialize decompress status for section .debug_info
collect2: error: ld returned 1 exit status

```

Linux x220 5.0.0-32-generic #34~18.04.2-Ubuntu SMP Thu Oct 10 10:36:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

I suggest just commenting the offending intrinsics until this compiler is released.

**Comment by moon-chilled** [comment]
Ok.

**Comment by p0nce** [comment]
Might be better for gdc now that implicit vector conversion are illegal in the regular DMDFE.

**Comment by p0nce** [comment]
Now it does compile, wait for the tag
