### ISSUE TITLE
_mm_prefetch only supports ldc

### ISSUE THREAD

**Issue by rikkimax** [AuburnSounds/intel-intrinsics#44]
It is not versioned and calls into LLVM intrinsic directly.

https://github.com/AuburnSounds/intel-intrinsics/blob/d73a7b2a42550af5efe4f2f6a2251fadd9ad875f/source/inteli/xmmintrin.d#L1059

https://software.intel.com/sites/landingpage/IntrinsicsGuide/#text=_mm_prefetch&expand=4391,4392,4393

DMD IASM does support prefetchnta prefetcht0 prefetcht1 prefetcht2

This may be a come up in the future if #41 was solved.

**Comment by p0nce** [comment]
I'm fixing _mm_prefetch

It's easy to write the DMD version, but this also leads to an interesting question.

My experience with prefetch (or non-temporal moves) is that you never gain anything when doing it manually. I think it would be faster to just do nothing when using DMD, this doesn't change program behaviour, and is likely faster. However, the user wanted a prefetch... we migt as well give one, like with LDC and GDC.

**Comment by p0nce** [comment]
Should be fixed with 198e07e480baae04086771f875c17acdf34e47c8 and v1.2.3

**Comment by p0nce** [comment]
LLVM version break the build when instantiated

**Comment by p0nce** [comment]
One more tag
