### ISSUE TITLE
_mm_srl_epi32 is too easy a trap to fall into

### ISSUE THREAD

**Issue by cerjones** [AuburnSounds/intel-intrinsics#46]
EDIT: 
Marked as deprecated:
- [x] __m128i _mm_sll_epi16 (__m128i a, __m128i count)
- [x] __m128i _mm_sll_epi32 (__m128i a, __m128i count)
- [x] __m128i _mm_sll_epi64 (__m128i a, __m128i count)
- [x] __m128i _mm_srl_epi16 (__m128i a, __m128i count)
- [x] __m128i _mm_srl_epi32 (__m128i a, __m128i count)
- [x] __m128i _mm_srl_epi64 (__m128i a, __m128i count)
- [x] __m128i _mm_sra_epi16 (__m128i a, __m128i count)
- [x] __m128i _mm_sra_epi32 (__m128i a, __m128i count)
- [x] and the MMX equivalent such as _mm_sra_pi32

------------------------------------

Im not sure if this is a bug or a weird implicit conversion, but the following code..

_m128i ipos;
uint lutshr =  11;
ipos = _mm_srl_epi32 (ipos, lutshr);

produces this asm...

000000013F8D1D96  movdqa      xmm0,xmmword ptr [rbp+110h]  
000000013F8D1D9E  mov         r8d,dword ptr [lutshr]  
000000013F8D1DA5  mov         dword ptr [rbp+0E0h],r8d  
000000013F8D1DAC  mov         dword ptr [rbp+0E4h],r8d  
000000013F8D1DB3  mov         dword ptr [rbp+0E8h],r8d  
000000013F8D1DBA  mov         dword ptr [rbp+0ECh],r8d  
000000013F8D1DC1  movdqa      xmm1,xmmword ptr [rbp+0E0h]  
000000013F8D1DC9  psrld       xmm0,xmm1 

The lutshr variable is being broadcast to each DWORD in the 2nd parameter passed to _mm_srl_epi32, this means when the shift is done with psrld at the end the actual shift count is wrong. What i think the docs say is that when the count is an XMM reg it actually reads the low 64 bits of the XMM reg, (god knows why) so it's getting "lutshr | (lutshr << 32)".

It can be worked around with declaring ipos like this...

 __m128i lutshr = [11,0,0,0];

so im not sure if its a bug or just weird side effect of implicit conversion of uint to _m128i

**Comment by p0nce** [comment]
I didn't know it but apparently a `uint` is implicitely converted to a `__vector(int[4])` here. Probably for convenience.

The intrinsics you are looking is `_mm_srli_epi32` not `_mm_srl_epi32`. 

I'm not sure how to avoid this user error, apart fninishing the DDoc definition? Having a fake overload just to catch this error sounds a bit overblown.

**Comment by cerjones** [comment]
Yeah its a bit weird that it broadcasts the single uint to each vector position. But then i didnt realise..

_m128 foo = 128.0; 

broadcasts to all positions too.

I think the issue is that given that it broadcasts the uint to each position in the vector, it is never going to be what you want. I cant see valid use case where you want the shift amount to be (x | (x shl 32), so I'd argue it passing in uint for count should be an error.

Tbh it doesnt matter  now as I've changed the code now anyway, I was doing the angle in integer and and shift down to get the gradient table lookup, but I've gone float till the last step because it allows any multiple repeats on the gradient, with integer it was limited to power of 2, now you can have any number of repeats.

**Comment by p0nce** [comment]
The following intrinsics are very error-prone indeed:
```
__m128i _mm_sll_epi16 (__m128i a, __m128i count)
__m128i _mm_sll_epi32 (__m128i a, __m128i count)
__m128i _mm_sll_epi64 (__m128i a, __m128i count)
__m128i _mm_srl_epi16 (__m128i a, __m128i count)
__m128i _mm_srl_epi32 (__m128i a, __m128i count)
__m128i _mm_srl_epi64 (__m128i a, __m128i count)
__m128i _mm_sra_epi16 (__m128i a, __m128i count)
__m128i _mm_sra_epi32 (__m128i a, __m128i count)
```

And at the very least need a warning. Since what the intrinsics is doing it barely useful...

**Comment by p0nce** [comment]
If we just remove these error-prone intrinsics, it would also solve #47 
and maps better to ARM shifts...
The "breakage" would probably find bugs too.
what do you think?

**Comment by p0nce** [comment]
Solved by deprecating these intrinsics in favor of the less error-prone.
