### ISSUE TITLE
Missing _mm_storeu_si32 intrinsic

### ISSUE THREAD

**Issue by ZILtoid1991** [AuburnSounds/intel-intrinsics#54]
I'm currently working on my CPUblit library to make it more readable and add some extra features, and while I was able to remove some clunky workaround in loading 32 bit values to 128 bit registers with the _mm_loadu_si32 intrinsic, _mm_storeu_si32 cannot be found there.

**Comment by p0nce** [comment]
Hello,

Thanks for the report! Indeed that's a strange omission.
The new intrinsic is now in v1.3.4
