### ISSUE TITLE
WASM: use WASM intrinsics for faster performance

### ISSUE THREAD

**Issue by JohanEngelen** [AuburnSounds/intel-intrinsics#77]
I just noticed that WASM also has SIMD support. (I'm not personally interested at the moment, but hope this helps someone in the future ;-)

Perhaps performance is already quite OK, but I can imagine that implementations of certain intrinsics can be improved by using WASM intrinsics.

https://v8.dev/features/simd
https://emscripten.org/docs/porting/simd.html

Looks like the LDC/LLVM attribute to add is "simd128": `-mattr=+simd128`. So that's `__traits(targetHasFeature, "simd128")`, and `version(WebAssembly)`.
https://d.godbolt.org/z/WrxP8EqMo

**Comment by p0nce** [comment]
Yes, simd-everywhere has support for this. It's a significant amount of work, and I'm not sure if the Webasm target supports the druntime?

**Comment by JohanEngelen** [comment]
No druntime support yet afaik (I think @skoppe has worked on it), but that's not needed for the intrinsics.

**Comment by p0nce** [comment]
It seems druntime doesn't build with wasm? 
![image](https://user-images.githubusercontent.com/1067485/125949117-e2dbd9aa-3e89-4cd4-9ecc-b6c1065d06c7.png)
This is with LDC 1.27-b3

**Comment by p0nce** [comment]
So it turns out when using WASM you can't use druntime nor libc... fun

**Comment by JohanEngelen** [comment]
yeah... this feature request is too soon, I think.

**Comment by p0nce** [comment]
mmm apart from _mm_malloc_ and _mm_free I see no difficulty (and of course the ever-difficult rounding functions)

**Comment by p0nce** [comment]
Impractical without a libc, since WASM builtin grow memory but do not malloc/free/realloc
