### ISSUE TITLE
Bug in greaterOrEqualMask

### ISSUE THREAD

**Issue by JohanEngelen** [AuburnSounds/intel-intrinsics#88]
I'm pretty sure there should be a `>=` on this line:
https://github.com/AuburnSounds/intel-intrinsics/blob/251936901d0ed70d2b5781db87337bf01ac87b5d/source/inteli/types.d#L426

**Comment by p0nce** [comment]
Good catch. 
I'm removing this `greaterOrEqualMask` emulation, as it wasn't used anywhere.
