### ISSUE TITLE
Unsupported instructions LDC: _mm_cmpgt_epi32 _mm_movq and _mm_movd

### ISSUE THREAD

**Issue by cerjones** [AuburnSounds/intel-intrinsics#9]
Hi, so far found a few instructions missing when using LDC, either not there or marked as TODO, not sure if you are aware but there is a work around using

https://wiki.dlang.org/LDC_inline_assembly_expressions

so far I've just needed these three, and not entirely sure I've doing it correctly but the output on compiler explorer so far matches OK,

int4 _mm_cmpgt_epi32(int4 a, int4 b) {
  return __asm!int4("pcmpgtd $2,$1", "=&x,x,x", a, b);
}

**fixed i think** Had the indexes wrong on the cmp,

int4 _mm_movq(void* a) {
  return __asm!int4("movq $1,$0", "=&x,*m", a);
}

int4 _mm_movd(void* a) {
  return __asm!int4("movd $1,$0", "=&x,*m", a);
}

I know you have functions that would do the two integer moves, but it was compiling to movsd rather than movq, and im not sure if that's an isssue or not.

**Comment by p0nce** [comment]
For missing _mm_something something important is to check how they are implemented in clang.
I'm not sure about the inline assembly, often it can lead to worse performance.

**Comment by p0nce** [comment]
Which intrinsics do you need exactly?
_mm_cmpgt_epi32
_mm_movq and
_mm_movd ?

**Comment by cerjones** [comment]
Tbh its not working as I expected anyway, it seems to cause registers to be overwritten that shouldnt be and I'm not sure why.

**Comment by cerjones** [comment]
yeah just those ones so far

**Comment by cerjones** [comment]
Ok dont know if this is of any use but it seems the only way to do it with inline assembler expression is by using an explicit temporary register, sadly it seems the optimiser cant cull that extra copy even if it's not actually needed.

__m128i _mm_cmpgt_epi32(__m128i a, __m128i b) {
    return __asm!int4("
        movdqu $1,$0
        pcmpgtd $2,$0",
        "=x,x,x", a,b);
}

**Comment by p0nce** [comment]
https://software.intel.com/sites/landingpage/IntrinsicsGuide/ < _mm_movq and _mm_movd do not exist....

I think you are looking for `_mm_loadu_si32` and `_mm_loadu_epi64` respectively, which are to be implemented granted.

**Comment by p0nce** [comment]
- [ ] _mm_loadu_si32 
- [ ] _mm_loadu_epi64
- [ ] _mm_cmpgt_epi32

**Comment by cerjones** [comment]
Awesome thanks,

**Comment by p0nce** [comment]
@cerjones, thanks for the __asm tutorial because it ended up being useful for 
```
     __m128i _mm_cvtps_epi32 (__m128 a) pure @trusted
    {
        return __asm!__m128i("cvtps2dq $1,$0","=x,x",a);
    }
```
